// <auto-generated />
using System;
using Bai2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bai2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bai2.Models.NGUOIQULY", b =>
                {
                    b.Property<int>("NguoiQuanLy_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguoiQuanLy_id"));

                    b.Property<string>("TenQuanLy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NguoiQuanLy_id");

                    b.ToTable("NGUOIQULYs");
                });

            modelBuilder.Entity("Bai2.Models.NHANVIEN", b =>
                {
                    b.Property<int>("Nhanvien_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Nhanvien_id"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<decimal>("Luong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Ma_NQL")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nhanvien_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PHG")
                        .HasColumnType("int");

                    b.HasKey("Nhanvien_id");

                    b.HasIndex("Ma_NQL");

                    b.HasIndex("PHG");

                    b.ToTable("NHANVIENs");
                });

            modelBuilder.Entity("Bai2.Models.PHONGBAN", b =>
                {
                    b.Property<int>("Phongban_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Phongban_id"));

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Phongban_id");

                    b.ToTable("PHONGBANs");
                });

            modelBuilder.Entity("Bai2.Models.THANNHAN", b =>
                {
                    b.Property<int>("ThanNhan_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThanNhan_id"));

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<int>("Nhanvien_id")
                        .HasColumnType("int");

                    b.Property<string>("QuanHe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenThanNhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ThanNhan_id");

                    b.HasIndex("Nhanvien_id");

                    b.ToTable("THANNHANs");
                });

            modelBuilder.Entity("Bai2.Models.NHANVIEN", b =>
                {
                    b.HasOne("Bai2.Models.NGUOIQULY", "NguoiQuanLy")
                        .WithMany("NhanViens")
                        .HasForeignKey("Ma_NQL")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_NHANVIEN_NGUOIQULY");

                    b.HasOne("Bai2.Models.PHONGBAN", "PhongBan")
                        .WithMany("NhanViens")
                        .HasForeignKey("PHG")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_NHANVIEN_PHONGBAN");

                    b.Navigation("NguoiQuanLy");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("Bai2.Models.THANNHAN", b =>
                {
                    b.HasOne("Bai2.Models.NHANVIEN", "NhanVien")
                        .WithMany("ThanNhans")
                        .HasForeignKey("Nhanvien_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_THANNHAN_NHANVIEN");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Bai2.Models.NGUOIQULY", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("Bai2.Models.NHANVIEN", b =>
                {
                    b.Navigation("ThanNhans");
                });

            modelBuilder.Entity("Bai2.Models.PHONGBAN", b =>
                {
                    b.Navigation("NhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
