// <auto-generated />
using System;
using Bai3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bai3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260118160913_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bai3.Models.DangKyKhoaHoc", b =>
                {
                    b.Property<int>("MaSinhVien")
                        .HasColumnType("int")
                        .HasColumnName("MaSinhVien");

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int")
                        .HasColumnName("MaKhoaHoc");

                    b.Property<DateTime>("NgayDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("NgayDangKy")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TrangThaiDangKy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Đã đăng ký")
                        .HasColumnName("TrangThaiDangKy");

                    b.HasKey("MaSinhVien", "MaKhoaHoc")
                        .HasName("PK_DangKyKhoaHoc");

                    b.HasIndex("MaKhoaHoc");

                    b.HasIndex("NgayDangKy")
                        .HasDatabaseName("IX_DangKyKhoaHoc_NgayDangKy");

                    b.HasIndex("TrangThaiDangKy")
                        .HasDatabaseName("IX_DangKyKhoaHoc_TrangThai");

                    b.HasIndex("MaSinhVien", "MaKhoaHoc")
                        .IsUnique()
                        .HasDatabaseName("UQ_DangKyKhoaHoc_SinhVien_KhoaHoc");

                    b.ToTable("DangKyKhoaHoc", null, t =>
                        {
                            t.HasCheckConstraint("CK_DangKyKhoaHoc_TrangThai", "[TrangThaiDangKy] IN (N'Đã đăng ký', N'Đã hủy', N'Chờ duyệt')");
                        });

                    b.HasData(
                        new
                        {
                            MaSinhVien = 1,
                            MaKhoaHoc = 1,
                            NgayDangKy = new DateTime(2024, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThaiDangKy = "Đã đăng ký"
                        },
                        new
                        {
                            MaSinhVien = 1,
                            MaKhoaHoc = 2,
                            NgayDangKy = new DateTime(2024, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThaiDangKy = "Đã đăng ký"
                        },
                        new
                        {
                            MaSinhVien = 2,
                            MaKhoaHoc = 2,
                            NgayDangKy = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThaiDangKy = "Đã đăng ký"
                        },
                        new
                        {
                            MaSinhVien = 2,
                            MaKhoaHoc = 3,
                            NgayDangKy = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThaiDangKy = "Đã đăng ký"
                        },
                        new
                        {
                            MaSinhVien = 3,
                            MaKhoaHoc = 1,
                            NgayDangKy = new DateTime(2024, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThaiDangKy = "Đã đăng ký"
                        });
                });

            modelBuilder.Entity("Bai3.Models.GiangVien", b =>
                {
                    b.Property<int>("MaGiangVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaGiangVien");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiangVien"));

                    b.Property<string>("ChuyenNganh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ChuyenNganh");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("HocVi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HocVi");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SoDienThoai");

                    b.Property<string>("TenGiangVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenGiangVien");

                    b.HasKey("MaGiangVien");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_GiangVien_Email");

                    b.HasIndex("SoDienThoai")
                        .IsUnique()
                        .HasDatabaseName("IX_GiangVien_SoDienThoai");

                    b.ToTable("GiangVien", (string)null);

                    b.HasData(
                        new
                        {
                            MaGiangVien = 1,
                            ChuyenNganh = "Toán học",
                            Email = "nguyenvana@university.edu",
                            HocVi = "Tiến sĩ",
                            SoDienThoai = "0912345678",
                            TenGiangVien = "TS. Nguyễn Văn A"
                        },
                        new
                        {
                            MaGiangVien = 2,
                            ChuyenNganh = "Công nghệ thông tin",
                            Email = "tranthib@university.edu",
                            HocVi = "Thạc sĩ",
                            SoDienThoai = "0923456789",
                            TenGiangVien = "ThS. Trần Thị B"
                        });
                });

            modelBuilder.Entity("Bai3.Models.KhoaHoc", b =>
                {
                    b.Property<int>("MaKhoaHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKhoaHoc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoaHoc"));

                    b.Property<decimal>("HocPhi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("HocPhi");

                    b.Property<int?>("MaGiangVien")
                        .HasColumnType("int")
                        .HasColumnName("MaGiangVien");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("date")
                        .HasColumnName("NgayBatDau");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("date")
                        .HasColumnName("NgayKetThuc");

                    b.Property<int>("SoTinChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3)
                        .HasColumnName("SoTinChi");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenKhoaHoc");

                    b.HasKey("MaKhoaHoc");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("NgayBatDau")
                        .HasDatabaseName("IX_KhoaHoc_NgayBatDau");

                    b.HasIndex("TenKhoaHoc")
                        .HasDatabaseName("IX_KhoaHoc_TenKhoaHoc");

                    b.ToTable("KhoaHoc", null, t =>
                        {
                            t.HasCheckConstraint("CK_KhoaHoc_Ngay", "[NgayKetThuc] IS NULL OR [NgayKetThuc] >= [NgayBatDau]");

                            t.HasCheckConstraint("CK_KhoaHoc_SoTinChi", "[SoTinChi] BETWEEN 1 AND 10");
                        });

                    b.HasData(
                        new
                        {
                            MaKhoaHoc = 1,
                            HocPhi = 1500000m,
                            MaGiangVien = 1,
                            NgayBatDau = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTinChi = 3,
                            TenKhoaHoc = "Toán cao cấp A1"
                        },
                        new
                        {
                            MaKhoaHoc = 2,
                            HocPhi = 2000000m,
                            MaGiangVien = 2,
                            NgayBatDau = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTinChi = 4,
                            TenKhoaHoc = "Lập trình C# nâng cao"
                        },
                        new
                        {
                            MaKhoaHoc = 3,
                            HocPhi = 1800000m,
                            MaGiangVien = 2,
                            NgayBatDau = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTinChi = 3,
                            TenKhoaHoc = "Cơ sở dữ liệu"
                        });
                });

            modelBuilder.Entity("Bai3.Models.SinhVien", b =>
                {
                    b.Property<int>("MaSinhVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaSinhVien")
                        .HasComment("Mã sinh viên");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSinhVien"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HoVaTen")
                        .HasComment("Họ và tên");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("NgaySinh");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SoDienThoai")
                        .HasComment("Số điện thoại");

                    b.HasKey("MaSinhVien");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_SinhVien_Email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("HoVaTen")
                        .HasDatabaseName("IX_SinhVien_HoVaTen");

                    b.ToTable("SinhVien", null, t =>
                        {
                            t.HasCheckConstraint("CK_SinhVien_NgaySinh", "[NgaySinh] <= GETDATE()");
                        });

                    b.HasData(
                        new
                        {
                            MaSinhVien = 1,
                            Email = "an.nguyen@student.edu",
                            HoVaTen = "Nguyễn Văn An",
                            NgaySinh = new DateTime(2000, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0934567890"
                        },
                        new
                        {
                            MaSinhVien = 2,
                            Email = "binh.tran@student.edu",
                            HoVaTen = "Trần Thị Bình",
                            NgaySinh = new DateTime(2001, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0945678901"
                        },
                        new
                        {
                            MaSinhVien = 3,
                            Email = "cuong.le@student.edu",
                            HoVaTen = "Lê Văn Cường",
                            NgaySinh = new DateTime(1999, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Bai3.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaThanhToan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("GhiChu");

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int")
                        .HasColumnName("MaKhoaHoc");

                    b.Property<int>("MaSinhVien")
                        .HasColumnType("int")
                        .HasColumnName("MaSinhVien");

                    b.Property<DateTime>("NgayThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("NgayThanhToan")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PhuongThucThanhToan");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SoTien");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Chưa thanh toán")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaThanhToan");

                    b.HasAlternateKey("MaSinhVien", "MaKhoaHoc", "NgayThanhToan")
                        .HasName("AK_ThanhToan_UniquePayment");

                    b.HasIndex("MaKhoaHoc");

                    b.HasIndex("NgayThanhToan")
                        .HasDatabaseName("IX_ThanhToan_NgayThanhToan");

                    b.HasIndex("TrangThai")
                        .HasDatabaseName("IX_ThanhToan_TrangThai");

                    b.HasIndex("MaSinhVien", "MaKhoaHoc")
                        .HasDatabaseName("IX_ThanhToan_SinhVien_KhoaHoc");

                    b.ToTable("ThanhToan", null, t =>
                        {
                            t.HasCheckConstraint("CK_ThanhToan_Ngay", "[NgayThanhToan] <= GETDATE()");

                            t.HasCheckConstraint("CK_ThanhToan_SoTien", "[SoTien] >= 0");

                            t.HasCheckConstraint("CK_ThanhToan_TrangThai", "[TrangThai] IN (N'Đã thanh toán', N'Chưa thanh toán', N'Đã hủy')");
                        });

                    b.HasData(
                        new
                        {
                            MaThanhToan = 1,
                            MaKhoaHoc = 1,
                            MaSinhVien = 1,
                            NgayThanhToan = new DateTime(2024, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhuongThucThanhToan = "Chuyển khoản",
                            SoTien = 1500000m,
                            TrangThai = "Đã thanh toán"
                        },
                        new
                        {
                            MaThanhToan = 2,
                            MaKhoaHoc = 2,
                            MaSinhVien = 1,
                            NgayThanhToan = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhuongThucThanhToan = "Tiền mặt",
                            SoTien = 1000000m,
                            TrangThai = "Đã thanh toán"
                        },
                        new
                        {
                            MaThanhToan = 3,
                            GhiChu = "Thanh toán đủ",
                            MaKhoaHoc = 2,
                            MaSinhVien = 2,
                            NgayThanhToan = new DateTime(2024, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTien = 2000000m,
                            TrangThai = "Đã thanh toán"
                        });
                });

            modelBuilder.Entity("Bai3.Models.DangKyKhoaHoc", b =>
                {
                    b.HasOne("Bai3.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("DangKyKhoaHocs")
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DangKyKhoaHoc_KhoaHoc");

                    b.HasOne("Bai3.Models.SinhVien", "SinhVien")
                        .WithMany("DangKyKhoaHocs")
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DangKyKhoaHoc_SinhVien");

                    b.Navigation("KhoaHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("Bai3.Models.KhoaHoc", b =>
                {
                    b.HasOne("Bai3.Models.GiangVien", "GiangVien")
                        .WithMany("KhoaHocs")
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_KhoaHoc_GiangVien");

                    b.Navigation("GiangVien");
                });

            modelBuilder.Entity("Bai3.Models.ThanhToan", b =>
                {
                    b.HasOne("Bai3.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ThanhToan_KhoaHoc");

                    b.HasOne("Bai3.Models.SinhVien", "SinhVien")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ThanhToan_SinhVien");

                    b.Navigation("KhoaHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("Bai3.Models.GiangVien", b =>
                {
                    b.Navigation("KhoaHocs");
                });

            modelBuilder.Entity("Bai3.Models.KhoaHoc", b =>
                {
                    b.Navigation("DangKyKhoaHocs");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("Bai3.Models.SinhVien", b =>
                {
                    b.Navigation("DangKyKhoaHocs");

                    b.Navigation("ThanhToans");
                });
#pragma warning restore 612, 618
        }
    }
}
