// <auto-generated />
using System;
using Lab2ModelBinding.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab2ModelBinding.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lab2ModelBinding.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerName = "Nguyễn Văn A",
                            OrderDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Processing"
                        },
                        new
                        {
                            OrderId = 2,
                            CustomerName = "Trần Thị B",
                            OrderDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        });
                });

            modelBuilder.Entity("Lab2ModelBinding.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderDetailId = 1,
                            OrderId = 1,
                            Price = 25000000m,
                            ProductName = "Laptop Dell XPS 13",
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 2,
                            OrderId = 1,
                            Price = 2500000m,
                            ProductName = "Chuột Logitech MX Master 3",
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 3,
                            OrderId = 2,
                            Price = 28000000m,
                            ProductName = "MacBook Air M2",
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("Lab2ModelBinding.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Laptop mỏng nhẹ cao cấp",
                            Name = "Laptop Dell XPS 13",
                            Price = 25000000m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Siêu phẩm Apple",
                            Name = "MacBook Air M2",
                            Price = 28000000m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Chuột công thái học",
                            Name = "Chuột Logitech MX Master 3",
                            Price = 2500000m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Bàn phím cơ không dây",
                            Name = "Bàn phím Keychron K2",
                            Price = 1800000m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Màn hình 4K sắc nét",
                            Name = "Màn hình LG UltraFine",
                            Price = 12000000m
                        });
                });

            modelBuilder.Entity("Lab2ModelBinding.Models.OrderDetail", b =>
                {
                    b.HasOne("Lab2ModelBinding.Models.Order", null)
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lab2ModelBinding.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
